[package]
name = "kct_kube"
version = "0.2.0"
authors = ["Bruno Felipe Leal Delfino <bruno.delfino1995@gmail.com>"]
description = "K8s object finder"
repository = "https://github.com/bruno-delfino1995/kct"
edition = "2018"
license = "MIT"

[dependencies]
serde = "1.0.115"
serde_json = "1.0"
thiserror = "1.0"
valico = "3.4.0"
