[package]
name = "kct_kube"
version = "0.1.0"
authors = ["Bruno Felipe Leal Delfino <bruno.delfino1995@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
serde = "1.0.115"
serde_json = "1.0"
thiserror = "1.0"
valico = "3.4.0"
