[package]
name = "kct"
description = "Kubernetes Configuration Tool"
keywords = ["kubernetes", "jsonnet"]
categories = ["command-line-utilities"]
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
serde = "1.0.115"
serde_json = "1.0"
serde_yaml = "0.8"
thiserror = "1.0"

kct_helper.workspace = true
kct_kube.workspace = true
kct_package.workspace = true
kct_compiler.workspace = true
