[package]
name = "kct"
description = "Kubernetes Configuration Tool"
keywords = ["kubernetes", "jsonnet"]
categories = ["command-line-utilities"]
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }

anyhow.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true

kct_helper.workspace = true
kct_kube.workspace = true
kct_package.workspace = true
kct_compiler.workspace = true
