[package]
name = "kct_helper"
description = "Utilities used by KCT components"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde_json = "1.0"
thiserror = "1.0"
