[package]
name = "kct_package"
version = "0.1.0"
authors = ["Bruno Felipe Leal Delfino <bruno.delfino1995@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
flate2 = "1.0.17"
globwalk = "0.8.0"
jrsonnet-evaluator = "0.3.1"
jrsonnet-parser = "0.3.1"
kct_helper = { path = "../kct_helper", version = "0.1.0" }
serde = "1.0.115"
serde_json = "1.0"
tar = "0.4.30"
tempfile = "3.1.0"
tera = "1"
url = "2.1.1"
valico = "3.4.0"
