# MIT License
#
# Copyright (c) 2020 Yaroslav Bolyukin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

on:
  push:
    tags:
      - v*

name: Release

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  release:
    needs: [test]
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl

          - i686-pc-windows-msvc
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl

          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        include:
          - target: aarch64-apple-darwin
            os: macOS-latest
            bin: kct
            name: kct-darwin-aarch64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            bin: kct
            name: kct-linux-gnu-aarch64
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            bin: kct
            name: kct-linux-musl-aarch64

          - target: i686-pc-windows-msvc
            os: windows-latest
            bin: kct.exe
            name: kct-windows-msvc-i686.exe
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
            bin: kct
            name: kct-linux-gnu-i686
          - target: i686-unknown-linux-musl
            os: ubuntu-latest
            bin: kct
            name: kct-linux-musl-i686

          - target: x86_64-apple-darwin
            os: macOS-latest
            bin: kct
            name: kct-darwin-amd64
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            bin: kct
            name: kct-linux-gnu-amd64
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            bin: kct
            name: kct-linux-musl-amd64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            bin: kct.exe
            name: kct-windows-msvc-amd64.exe
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Cache cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Linux x86 cross compiler
        if: ${{ startsWith(matrix.target, 'i686-unknown-linux-') }}
        run: sudo apt install gcc-multilib

      - name: ARM cross compiler
        if: ${{ startsWith(matrix.target, 'aarch64-unknown-linux-') }}
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cross

      - name: ARM gcc
        if: ${{ startsWith(matrix.target, 'aarch64-unknown-linux-') }}
        run: sudo apt install gcc-aarch64-linux-gnu

      - name: Musl gcc
        if: ${{ endsWith(matrix.target, '-musl') }}
        run: sudo apt install musl musl-tools

      - name: Run cross build
        if: ${{ startsWith(matrix.target, 'aarch64-unknown-linux-') }}
        shell: bash
        run: cross build --bin=kct --release --target ${{ matrix.target }}

      - name: Run build
        if: ${{ !startsWith(matrix.target, 'aarch64-unknown-linux-') }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin=kct --release --target ${{ matrix.target }}

      - name: Create packages
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          cp ${{ matrix.bin }} ../../../${{ matrix.name }}

      - name: Generate SHA-256
        run: shasum -a 256 ${{ matrix.name }} > ${{ matrix.name }}.sha256

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "kct*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
