# MIT License
#
# Copyright (c) 2020 Yaroslav Bolyukin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

on:
  push:
    tags:
      - v*

name: Release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  github-release:
    needs: [test]
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rust: nightly
            target: x86_64-unknown-linux-musl
            bin: kct
            name: kct-linux-amd64
          - os: windows-latest
            rust: nightly
            target: x86_64-pc-windows-msvc
            bin: kct.exe
            name: kct-windows-amd64.exe
          - os: macOS-latest
            rust: nightly
            target: x86_64-apple-darwin
            bin: kct
            name: kct-darwin-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          target: ${{ matrix.target }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin=kct --release --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          strip target/${{ matrix.target }}/release/${{ matrix.bin }}
          cd target/${{ matrix.target }}/release

          cp ${{ matrix.bin }} ../../../${{ matrix.name }}
          cd -
      - name: Generate SHA-256
        run: shasum -a 256 ${{ matrix.name }} > ${{ matrix.name }}.sha256
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "kct*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
